// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroBlazorWebApp.Server.Models.Context;

#nullable disable

namespace SuperHeroBlazorWebApp.Server.Migrations
{
    [DbContext(typeof(SuperHeroBlazorContext))]
    [Migration("20230927205018_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6");

            modelBuilder.Entity("SuperHeroBlazorWebApp.Shared.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuperHeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SuperHeroId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("SuperHeroBlazorWebApp.Shared.Models.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SuperHeroes");
                });

            modelBuilder.Entity("SuperHeroBlazorWebApp.Shared.Models.Movie", b =>
                {
                    b.HasOne("SuperHeroBlazorWebApp.Shared.Models.SuperHero", "SuperHero")
                        .WithMany("Movies")
                        .HasForeignKey("SuperHeroId");

                    b.Navigation("SuperHero");
                });

            modelBuilder.Entity("SuperHeroBlazorWebApp.Shared.Models.SuperHero", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
